import type { ErpState } from "./types";
import referenceData from "./reference-data.json";

export const demoState: ErpState = {
  warehouses: ["义乌一仓", "广州仓", "川崎日本倉庫"],
  skus: referenceData.skus.map((sku) => ({ fnsku: "", ...sku })),
  orders: referenceData.orders as ErpState["orders"],
  stocks: referenceData.stocks,
  inventorySnapshots: [
    {
      id: "inventory-demo-1",
      fnsku: "XMK-BDK-H-11",
      sellerSku: "XMK-BDK-H-11",
      skuCode: undefined,
      productName: "康-黑色带扣背带裤",
      warehouseName: "川崎日本倉庫",
      dropshipTransitQty: 0,
      dropshipStockQty: 11,
      transferTransitQty: 0,
      transferStockQty: 0,
      pendingQty: 0,
      sales10d: 0,
      sales30d: 5,
      stockAgeDays: 28,
      volume: 0.017,
      sourceWarningQty: 0,
      inboundAt: "2026-05-26 12:52:05",
      matchedStatus: "未匹配",
    },
  ],
  inventoryImportJobs: [],
  movements: [],
  shipments: [],
  shipmentDrafts: referenceData.shipmentDrafts,
  purchases: [
    {
      id: "po-1",
      purchaseNo: "PO-20260615-001",
      skuCode: "YC2001",
      quantity: 20,
      receivedQty: 0,
      unitPrice: 42,
      supplier: "广州佳衣",
      expectedAt: "2026-06-25",
      status: "已下单",
      carrier: "顺丰",
      domesticTrackNo: "SF-DEMO-001",
      internationalNo: "",
    },
  ],
  audits: [],
};
