-- AlterEnum
ALTER TYPE "AppModule" ADD VALUE 'warehouseAdmin';

-- AlterTable
ALTER TABLE "Warehouse" ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Warehouse" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
